### ISSUE TITLE
Not getting any display in Magic Mirror

### ISSUE THREAD

**Issue by tgabben** [mrVragec/MMM-uptimerobot#1]
Full disclosure - I might just be dumb - but even when loading this module in barebones (api_key only under config: - using the Main API key from my newly minted uptimerobot account) - I don't get any squawking errors, but I also don't get... well, anything, really.

Is there perhaps a very obvious thing I missed?

**Comment by hnoesekabel** [comment]
Hi,

had the same issue - renaming uptimerobot.js to MMM-uptimerobot.js plus changing how the module registers worked for me.

Run this in your cloned project folder:
`mv uptimerobot.js MMM-uptimerobot.js`

Then change MMM-uptimerobot.js to this in line 8, right after the header comment:
`Module.register("MMM-uptimerobot", {`

This error is not dumped in the shell when executing MagicMirror but rather in the Electron app console... to see it, press e.g. on a Mac CMD-ALT-I when viewing your MagicMirror app - same combination for pulling up dev tools in Chrome.

Hope that helps!

**Comment by mrVragec** [comment]
@hnoesekabel: You are right, there was a typo in README file (using MMM-template). Fix will be ready shortly. 
BTW: Right now there is an issue with using icons (config useIcons: true); also this issue will be fixed with next commit.

**Comment by tgabben** [comment]
@hnoesekabel - 
a very thorough explanation, and right on the nose! Thanks very much for pointing me in the right direction - was definitely getting a bit lost in the weeds. I am getting the display I was looking for, now.

@mrVragec - thanks for your work on this module - I love the idea of the Magic Mirror project, and I find your project to be extremely practical for my intended use. I'm finding the opposite of your comment, actually - I am having success with useIcons (at least the 'Online' icon). 'useColours: true' doesn't appear to have any effect, though. (I don't know if it's meant to effect the icon, but it seems to have no effect on the text-only view or the icon view).

**Comment by mrVragec** [comment]
@tgabben with option 'useIcons: true' you should see icons instead of text and with option 'useColors: true' icons or text should be green (online) or red (offline) (and other colors for different status). I just added screenshots so you can see a different between useIcons and useColors options.

**Comment by tgabben** [comment]
@mrVragec that's what I figured - just was allowing for the possibility that the options were mutually exclusive. 

Again - I'm finding that the 'Online' icon **is** displaying (let's hope i rarely, if ever, have to see any other icon) - but I even double-checked to be sure I hadn't used the Canadian/British spelling of 'colours' (as in my comment above) - but the colour display isn't showing either for icons or text.

**Comment by tgabben** [comment]
This is resolved for me - just noticed that you'd posted new instructions w/the code, to rename the folder and the module title in the main config (the inverse of @hnoesekabel's fix from earlier than got the module to load in the first place) - must have been another case where the MMM-uptimerobot vs. uptimerobot thing wasn't calling the right .css file, because both icons and colours are now working as intended!

rm -rf'd for good measure within /modules, re-cloned from git to get your fixes, and after re-naming the cloned folder to 'uptimerobot', all is well.

Thanks!
